---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb-pod
  labels:
    env: dev
spec:
  containers:
    - name: mongodb
      image: mongodb/mongodb-community-server:latest
      ports:
        - name: mongoport
          protocol: TCP
          containerPort: 27017
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: password
        - name: ME_CONFIG_MONGODB_URL
          value: mongodb://root:example@mongo:27017/
      resources:
        requests:
          cpu: 200m
          memory: 512M
        limits:
          cpu: 400m
          memory: 1G
      volumeMounts:
        - name: mongovol
          mountpath: /data/db
  volumes:
    - name: mongovol
      persistentVolumeClaim:
        claimName: mongodbpvc